// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  EvalProgram = 1,
  Reference = 2,
  Identifier = 3,
  Lambda = 4,
  BooleanLiteral = 5,
  LetExpression = 6,
  Number = 7,
  String = 8,
  Escape = 9,
  BinaryExpression = 10,
  Call = 12,
  UnaryExpression = 25,
  ParenthesizedExpression = 26,
  ArgList = 29
