// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  EvalProgram = 1,
  Reference = 2,
  Identifier = 3,
  Lambda = 4,
  ConstantLiteral = 5,
  LetExpression = 6,
  VariableAssignment = 7,
  Number = 8,
  String = 9,
  Escape = 10,
  ArrayExpression = 11,
  ObjectExpression = 12,
  UnaryExpression = 13,
  BinaryExpression = 14,
  Call = 16,
  ParenthesizedExpression = 30,
  ArgList = 33
